# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :start_CD do 
    login
    beta
  end

  desc "Login to app store"
  lane :login do
    app_store_connect_api_key(
    key_id: "WDT2KD4ABB",
    issuer_id: "ad85ea0e-0ed0-4e13-89cd-9ebf683da84d",
    key_filepath: "./AuthKey_WDT2KD4ABB.p8",
    duration: 1200,
    in_house: false)
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Fruits.xcodeproj")
    build_app(scheme: "Fruits")
    upload_to_testflight
  end
end
